# Model arguments
model_name_or_path: /data/horse/ws/hama901h-BFTranslation/checkpoints/meta-llama/Llama-3.1-8B/tulu3/w_checkpoints/Rank256/alpha_5e5_010/final
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_splits:
- train
- test
preprocessing_num_workers: 1

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: false
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 512
num_train_epochs: 3
optim: adamw_torch
output_dir: /data/horse/ws/hama901h-BFTranslation/checkpoints/meta-llama/Llama-3.1-8B/tulu3/w_checkpoints/Rank256/alpha_5e5_010/TRL_DPO/
overwrite_output_dir: false
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
save_strategy: "steps"
save_steps: 200
save_total_limit: 20
seed: 42
warmup_ratio: 0.1