# Model arguments
model_name_or_path: /data/cat/ws/hama901h-Posttraining/checkpoints/1.7b-MixtureVitae-300BT-v1
# model_revision: main
torch_dtype: bfloat16
trust_remote_code: true

# Data training arguments
chat_template: "{% for message in messages %}{% if message['role'] == 'system' %}{{ '<|system|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'user' %}{{ '<|user|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'assistant' %}{% if not loop.last %}{{ '<|assistant|>\n'  + message['content'] + eos_token + '\n' }}{% else %}{{ '<|assistant|>\n'  + message['content'] + eos_token }}{% endif %}{% endif %}{% if loop.last and add_generation_prompt %}{{ '<|assistant|>\n' }}{% endif %}{% endfor %}"

dataset_name:
  allenai/tulu-3-sft-mixture
dataset_test_split_size: 0.02
dataset_test_split_seed: 42

# SFT trainer config
bf16: true
eval_strategy: "steps"
eval_steps: 50
learning_rate: 7e-7
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: linear
max_length: 4096
max_steps: -1
num_train_epochs: 2
output_dir: /data/cat/ws/hama901h-Posttraining/checkpoints/1.7b-MixtureVitae-300BT-v1/tulu3-sft/LR7e7/
overwrite_output_dir: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
save_strategy: "steps"
save_steps: 200
save_total_limit: 100
seed: 42
warmup_ratio: 0.03
