# Model arguments
model_name_or_path: /home/hk-project-p0024043/hgf_ivw0083/ws/hkfswork/hgf_ivw0083-finetuning/checkpoints/Llama-3.1-Tulu-3-8B-SFT
torch_dtype: bfloat16

# # Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixture:
  datasets:                     
    - id: allenai/llama-3.1-tulu-3-8b-preference-mixture
      split: train 
      config: default    
      weight: 1.0
# dataset_name: allenai/llama-3.1-tulu-3-8b-preference-mixture
# dataset_splits:
#   - train
dataset_num_proc: 16

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: false
# eval_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /home/hk-project-p0024043/hgf_ivw0083/ws/hkfswork/hgf_ivw0083-finetuning/checkpoints/Llama-3.1-Tulu-3-8B-SFT/dpo/tulu3-pref-mix-8b/
overwrite_output_dir: false
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
save_strategy: "steps"
save_steps: 500
save_total_limit: 20
seed: 42
warmup_ratio: 0.1