# Model arguments
model_name_or_path: /scratch/project_462000353/zosaelai2/models/openeurollm-datamix-2b-en-90pct
# model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{{ bos_token }}\n{%- if messages[0]['role'] == 'system' -%}\n    {%- if messages[0]['content'] is string -%}\n        {%- set first_user_prefix = messages[0]['content'] + '\n\n' -%}\n    {%- else -%}\n        {%- set first_user_prefix = messages[0]['content'][0]['text'] + '\n\n' -%}\n    {%- endif -%}\n    {%- set loop_messages = messages[1:] -%}\n{%- else -%}\n    {%- set first_user_prefix = \"\" -%}\n    {%- set loop_messages = messages -%}\n{%- endif -%}\n{%- for message in loop_messages -%}\n    {%- if (message['role'] == 'user') != (loop.index0 % 2 == 0) -%}\n        {{ raise_exception(\"Conversation roles must alternate user/assistant/user/assistant/...\") }}\n    {%- endif -%}\n    {%- if (message['role'] == 'assistant') -%}\n        {%- set role = \"model\" -%}\n    {%- else -%}\n        {%- set role = message['role'] -%}\n    {%- endif -%}\n    {{ '<start_of_turn>' + role + '\n' + (first_user_prefix if loop.first else \"\") }}\n    {%- if message['content'] is string -%}\n        {{ message['content'] | trim }}\n    {%- elif message['content'] is iterable -%}\n        {%- for item in message['content'] -%}\n            {%- if item['type'] == 'image' -%}\n                {{ '<start_of_image>' }}\n            {%- elif item['type'] == 'text' -%}\n                {{ item['text'] | trim }}\n            {%- endif -%}\n        {%- endfor -%}\n    {%- else -%}\n        {{ raise_exception(\"Invalid content type\") }}\n    {%- endif -%}\n    {{ '<end_of_turn>\n' }}\n{%- endfor -%}\n{%- if add_generation_prompt -%}\n    {{'<start_of_turn>model\n'}}\n{%- endif -%}\n"
dataset_mixture:
  datasets:
    - id: /scratch/project_462000353/posttraining_data/SFTTrainer_format/eng/tulu-3-sft-mixture-commercial
      config: default
      split: train            
      columns:
        - messages
      weight: 1.0
dataset_num_proc: 8

# SFT trainer config
bf16: true
eval_strategy: 'no'
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
gradient_accumulation_steps: 2
gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: false
learning_rate: 2.0e-5 # 3e-4
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 8192
max_steps: -1
num_train_epochs: 2
output_dir: data/openeurollm-datamix-2b-en-90pct-SFT-tulu3-en-epochs-3
overwrite_output_dir: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
# push_to_hub: true
remove_unused_columns: true
# report_to:
# - tensorboard
save_strategy: "steps"
save_steps: 200
save_total_limit: 2
seed: 42
warmup_ratio: 0.03