# Model arguments
model_name_or_path: /data/horse/ws/hama901h-BFTranslation/checkpoints/datamix-9b-60-40/alignment-handbook/tulu3-sft
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_name:
  allenai/llama-3.1-tulu-3-8b-preference-mixture
# dataset_splits:
# - train
# preprocessing_num_workers: 8

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: false
# eval_strategy: epoch
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir:  /data/horse/ws/hama901h-BFTranslation/checkpoints/datamix-9b-60-40/alignment-handbook/tulu3-sft/DPO/
overwrite_output_dir: false
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
save_strategy: "steps"
save_steps: 500
save_total_limit: 20
seed: 8
warmup_ratio: 0.1