# Model arguments
model_name_or_path: /scratch/project_462000353/zosaelai2/models/Apertus-8B-2509
# model_revision: main
# torch_dtype: bfloat16
# attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}" 
dataset_mixture:
  datasets:
    - id: /scratch/project_462000353/posttraining_data/SFTTrainer_format/multiling/europa_sft_mix
      config: default
      split: train            
      columns:
        - messages
      weight: 1.0
dataset_num_proc: 5

# SFT trainer config
bf16: true
eval_strategy: 'no'
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
gradient_accumulation_steps: 2
gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: false
learning_rate: 2.0e-5 # 3e-4
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 8192
max_steps: -1
num_train_epochs: 2
output_dir: data/Apertus-8B-Europa-SFT-mix
overwrite_output_dir: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
# push_to_hub: true
remove_unused_columns: true
# report_to:
# - tensorboard
save_strategy: "steps"
save_steps: 200
save_total_limit: 2
seed: 42
warmup_ratio: 0.03